server:

  port: 8000
  
logging:
  level:
    root: debug
    com.sec.aip.aipmaster: debug
    
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2